name: Docker Image CI

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  #For manual run
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull new Master
      run: |
        cd /home/ubuntu/BotFersal
        git pull

    - name: Check container_last_id
      run: |
        cd /home/ubuntu/expense_bot/ExpenseBot
        if cat container_last_id.txt ; then
          cat container_last_id.txt | xargs -t sudo docker stop
          cat container_last_id.txt | xargs -t sudo docker rm -f 
        else
          echo "this will be the first container"
        fi

    - name: Remove python:bot_fersal
      run: |
        result=$(sudo docker images -q python:bot_fersal)
        
        if [[ -n "$result" ]]; then
          sudo docker image rm -f python:bot_fersal
        else
           echo "No such container image"
        fi

    - name: Build docker image
      run: sudo docker image build -t python:bot_fersal /home/ubuntu/BotFersal

    - name: run docker
      run: sudo docker run -d --name expense_bot -it python:bot_fersal

    - name: Log docker ID
      run: |
        cd /home/ubuntu/BotFersal
        sudo docker ps -q -f name=bot_fersal > container_last_id.txt
