name: ORANGE PI Docker Image CI 

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  #For manual run
  workflow_dispatch:
jobs:

  build:
  
    runs-on: self-hosted

    steps:
      - name: Pull new Master
        run: |
          cd /home/orangepi/BotFersal
          git pull

     - name: Set secrets in appSettings.py
        run: |
          sed -i "s|REPLACE_WITH_BOT_TOKEN|${{ secrets.botToken }}|g" /home/orangepi/BotFersal/appSettings.py
          sed -i "s|REPLACE_WITH_MONGO_CONNECTION_STRING|${{ secrets.mongo_connection_string }}|g" /home/orangepi/BotFersal/appSettings.py
          sed -i "s|REPLACE_WITH_TEN_BIS_MAIL|${{ secrets.ten_bis_mail }}|g" /home/orangepi/BotFersal/appSettings.py
          sed -i "s|REPLACE_WITH_USER_NAME|${{ secrets.user_name }}|g" /home/orangepi/BotFersal/appSettings.py

      - name: Remove python:bot_fersal
        run: |
          result=$(sudo docker images -q python:bot_fersal)
          if [[ -n "$result" ]]; then
            sudo docker image rm -f python:bot_fersal
          else
            echo "No such container image"
          fi

      - name: Build docker image
        run: sudo docker image build -t python:bot_fersal /home/orangepi/BotFersal

      - name: Run docker
        run: sudo docker run -d --name expense_bot -it python:bot_fersal

      - name: Log docker ID
        run: |
          cd /home/orangepi/BotFersal
          sudo docker ps -q -f name=bot_fersal > container_last_id.txt
